import { Pressable } from '@/tw';
import { useRouter, type Href } from 'expo-router';
import { Icon } from './Icon';

export function SearchButton() {
  const router = useRouter();
  // The literal route is cast to Href because Expo Router's typed-routes
  // cache (`.expo/types/router.d.ts`) is regenerated by `npx expo start`,
  // not by `expo export`. The cast is harmless at runtime — the file at
  // app/search.tsx maps directly to the `/search` path.
  return (
    <Pressable
      onPress={() => router.push('/search' as Href)}
      className="px-3"
      accessibilityRole="button"
      accessibilityLabel="Search screenshots"
    >
      <Icon name="magnifyingglass" size={22} tintColor="#0f172a" />
    </Pressable>
  );
}
