import { Pressable, Text } from 'react-native';
import { useRouter, type Href } from 'expo-router';

/**
 * Magnifier icon shown in the right-side of the Inbox and Trip Detail
 * headers. Pushes the dedicated /search screen — search is global, no
 * trip pre-filter is applied even when launched from a trip view.
 */
export function SearchButton() {
  const router = useRouter();
  // The literal route is cast to Href because Expo Router's typed-routes
  // cache (`.expo/types/router.d.ts`) is regenerated by `npx expo start`,
  // not by `expo export`. The cast is harmless at runtime — the file at
  // app/search.tsx maps directly to the `/search` path.
  return (
    <Pressable
      onPress={() => router.push('/search' as Href)}
      className="px-3"
      accessibilityRole="button"
      accessibilityLabel="Search screenshots"
    >
      <Text className="text-xl text-slate-900">🔍</Text>
    </Pressable>
  );
}
